# Host unit tests for the Arduino-free keypad logic. See ../common/host_tests.mk.

NAME := keypad_tests
# Pure firmware sources under test. They must not include Arduino.h.
FIRMWARE_SRCS := keypad_input.cpp keypad_keymap.cpp

include ../common/host_tests.mk
