#!/usr/bin/env python3
"""
generate_voice_data_v3_fixed.py

Fixes symbol naming so "voice_am.wav" -> voice_am (no _wav suffix in symbols).

Converts voice_*.wav files into an Arduino-compatible voice_data.h

Features:
- Forces mono
- Converts to 16-bit PCM
- Resamples to 11025 Hz (default, configurable)
- Generates PROGMEM uint8_t arrays: voice_x / voice_x_len
- Optional export of converted WAV files for listening verification

Dependencies:
  pip install numpy soundfile
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import numpy as np
import soundfile as sf

DEFAULT_TARGET_SR = 11025


def sanitize_symbol(filename: str) -> str:
    """
    Robustly derive the C symbol from the WAV filename.

    Examples:
      voice_am.wav -> voice_am
      Voice-USB.WAV -> voice_usb
    """
    # IMPORTANT FIX: use Path(...).stem to remove the extension reliably
    base = Path(filename).stem.lower()
    base = re.sub(r"[^a-z0-9_]+", "_", base)
    base = re.sub(r"_+", "_", base).strip("_")
    if not base.startswith("voice_"):
        base = "voice_" + base
    return base


def resample_linear(data: np.ndarray, sr: int, target_sr: int) -> np.ndarray:
    if sr == target_sr:
        return data
    if len(data) < 2:
        return data
    ratio = target_sr / float(sr)
    x_old = np.linspace(0.0, 1.0, num=len(data), endpoint=True)
    x_new = np.linspace(0.0, 1.0, num=max(2, int(len(data) * ratio)), endpoint=True)
    return np.interp(x_new, x_old, data).astype(np.float32)


def load_wav_as_pcm16_mono(path: Path, target_sr: int) -> np.ndarray:
    """
    Returns int16 mono PCM at target_sr.
    """
    data, sr = sf.read(path, dtype="float32", always_2d=False)

    # Force mono (take left channel if multichannel)
    if hasattr(data, "ndim") and data.ndim > 1:
        data = data[:, 0]

    # Resample
    data = resample_linear(data.astype(np.float32), sr, target_sr)

    # Clip and convert to PCM16
    data = np.clip(data, -1.0, 1.0)
    pcm16 = (data * 32767.0).astype(np.int16)
    return pcm16


def pcm16_to_u8_bytes_le(pcm16: np.ndarray) -> np.ndarray:
    pcm16_le = pcm16.astype("<i2", copy=False)  # ensure little-endian
    return np.frombuffer(pcm16_le.tobytes(), dtype=np.uint8)


def format_c_array(u8: np.ndarray, cols: int = 16) -> str:
    hex_bytes = [f"0x{b:02X}" for b in u8.tolist()]
    lines = []
    for i in range(0, len(hex_bytes), cols):
        lines.append(", ".join(hex_bytes[i:i + cols]))
    return ",\n  ".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate voice_data.h from voice_*.wav (mono PCM16 @ target_sr).")
    ap.add_argument("--in", dest="in_dir", default=".", help="Input folder containing voice_*.wav (default: .)")
    ap.add_argument("--out", dest="out_file", default="voice_data.h", help="Output header (default: voice_data.h)")
    ap.add_argument("--target-sr", type=int, default=DEFAULT_TARGET_SR, help=f"Target sample rate (default: {DEFAULT_TARGET_SR})")
    ap.add_argument("--write-wav", action="store_true", help="Also write converted WAV files (mono PCM16 @ target_sr)")
    ap.add_argument("--wav-out", default="converted_wav", help="Output folder for converted WAV files (default: converted_wav)")
    args = ap.parse_args()

    in_dir = Path(args.in_dir).expanduser().resolve()
    out_file = Path(args.out_file).expanduser().resolve()
    target_sr = int(args.target_sr)

    wav_files = sorted(in_dir.glob("voice_*.wav"))
    if not wav_files:
        raise SystemExit(f"No files matching voice_*.wav found in: {in_dir}")

    wav_out_dir = None
    if args.write_wav:
        wav_out_dir = Path(args.wav_out).expanduser().resolve()
        wav_out_dir.mkdir(parents=True, exist_ok=True)

    h = []
    h.append("// AUTO-GENERATED by generate_voice_data_v3_fixed.py")
    h.append("#pragma once")
    h.append("#include <stddef.h>")
    h.append("#include <stdint.h>")
    h.append("")
    h.append("#ifndef PROGMEM")
    h.append("  #define PROGMEM")
    h.append("#endif")
    h.append("")
    h.append(f"// Audio format: mono, PCM16 LE, {target_sr} Hz")
    h.append("")

    for wav in wav_files:
        symbol = sanitize_symbol(wav.name)
        pcm16 = load_wav_as_pcm16_mono(wav, target_sr)
        u8 = pcm16_to_u8_bytes_le(pcm16)

        if wav_out_dir is not None:
            sf.write(wav_out_dir / wav.name, pcm16, target_sr, subtype="PCM_16")

        h.append(f"#define HAS_VOICE_{symbol} 1")
        h.append(f"const uint8_t {symbol}[] PROGMEM = {{")
        h.append("  " + format_c_array(u8, cols=16))
        h.append("};")
        h.append(f"const size_t {symbol}_len = sizeof({symbol});")
        h.append("")

    out_file.write_text("\n".join(h), encoding="utf-8")
    print(f"OK: wrote {out_file}")
    if wav_out_dir is not None:
        print(f"OK: wrote converted WAV files to {wav_out_dir}")
    print(f"Target sample rate: {target_sr} Hz")
    print(f"Processed files: {len(wav_files)}")


if __name__ == "__main__":
    main()
