# Host unit tests for the Arduino-free FT-8x7 CAT and EEPROM decoding. See ../common/host_tests.mk.

NAME := ft8x7_tests
# Pure firmware sources under test. They must not include Arduino.h.
FIRMWARE_SRCS := ft8x7_codec.cpp

include ../common/host_tests.mk
