# Host unit tests for the built-in radio profile table. See ../common/host_tests.mk.

NAME := profile_tests
# Pure firmware sources under test. They must not include Arduino.h.
FIRMWARE_SRCS := radio_profile_table.cpp

include ../common/host_tests.mk
