#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import wave
from pathlib import Path

import numpy as np

ALIASES = {
    "a_m": "am",
    "s_meter": "s_meter",
    "thank_you": "thankyou",
    "v_f_o": "vfo",
}


def sanitize_symbol(filename: str) -> str:
    base = Path(filename).stem.lower()
    base = re.sub(r"[^a-z0-9_]+", "_", base)
    base = re.sub(r"_+", "_", base).strip("_")
    base = ALIASES.get(base, base)
    if not base.startswith("voice_"):
        base = "voice_" + base
    return base


def load_wav_as_pcm16_mono(path: Path) -> np.ndarray:
    with wave.open(str(path), "rb") as wav_file:
      channels = wav_file.getnchannels()
      sampwidth = wav_file.getsampwidth()
      frames = wav_file.getnframes()
      if channels != 1:
          raise ValueError(f"{path} is not mono")
      if sampwidth != 2:
          raise ValueError(f"{path} is not 16-bit PCM")
      raw = wav_file.readframes(frames)
    return np.frombuffer(raw, dtype="<i2")


def pcm16_to_u8_bytes_le(pcm16: np.ndarray) -> np.ndarray:
    return np.frombuffer(pcm16.astype("<i2", copy=False).tobytes(), dtype=np.uint8)


def format_c_array(u8: np.ndarray, cols: int = 16) -> str:
    hex_bytes = [f"0x{b:02X}" for b in u8.tolist()]
    lines = []
    for i in range(0, len(hex_bytes), cols):
        lines.append(", ".join(hex_bytes[i:i + cols]))
    return ",\n  ".join(lines)


def generate_header_blocks(in_dir: Path) -> dict[str, str]:
    blocks: dict[str, str] = {}
    for wav_path in sorted(in_dir.glob("voice_*.wav")):
        symbol = sanitize_symbol(wav_path.name)
        pcm16 = load_wav_as_pcm16_mono(wav_path)
        u8 = pcm16_to_u8_bytes_le(pcm16)
        block = "\n".join(
            [
                f"#define HAS_VOICE_{symbol} 1",
                f"const uint8_t {symbol}[] PROGMEM = {{",
                "  " + format_c_array(u8, cols=16),
                "};",
                f"const size_t {symbol}_len = sizeof({symbol});",
                "",
            ]
        )
        blocks[symbol] = block
    return blocks


def parse_existing_blocks(old_header: Path) -> tuple[str, list[str], dict[str, str]]:
    text = old_header.read_text(encoding="utf-8")
    pieces = re.split(r"(?=^#define HAS_VOICE_)", text, flags=re.MULTILINE)
    prefix = pieces[0]
    order: list[str] = []
    blocks: dict[str, str] = {}
    for piece in pieces[1:]:
        match = re.match(r"#define HAS_VOICE_(voice_[a-z0-9_]+)\s+1", piece)
        if not match:
            continue
        symbol = match.group(1)
        order.append(symbol)
        blocks[symbol] = piece.rstrip() + "\n"
    return prefix, order, blocks


def main() -> None:
    ap = argparse.ArgumentParser(description="Build merged voice_data.h from generated voice_*.wav clips.")
    ap.add_argument("--in", dest="in_dir", required=True, help="Folder containing voice_*.wav")
    ap.add_argument("--base", dest="base_header", required=True, help="Existing voice_data.h to merge into")
    ap.add_argument("--out", dest="out_file", required=True, help="Output merged voice_data.h")
    ap.add_argument("--target-sr", type=int, default=11025, help="Metadata sample rate comment")
    args = ap.parse_args()

    in_dir = Path(args.in_dir).resolve()
    base_header = Path(args.base_header).resolve()
    out_file = Path(args.out_file).resolve()

    new_blocks = generate_header_blocks(in_dir)
    prefix, existing_order, existing_blocks = parse_existing_blocks(base_header)

    prefix_lines = [
        "// AUTO-GENERATED by build_voice_data.py",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "#ifndef PROGMEM",
        "  #define PROGMEM",
        "#endif",
        "",
        f"// Audio format: mono, PCM16 LE, {args.target_sr} Hz",
        "",
    ]
    if "#pragma once" in prefix:
        output_parts = ["\n".join(prefix_lines) + "\n"]
    else:
        output_parts = [prefix]

    emitted: set[str] = set()
    for symbol in existing_order:
        if symbol in new_blocks:
            output_parts.append(new_blocks[symbol])
        else:
            output_parts.append(existing_blocks[symbol])
        emitted.add(symbol)

    for symbol in sorted(new_blocks):
        if symbol not in emitted:
            output_parts.append(new_blocks[symbol])

    out_file.write_text("".join(output_parts).rstrip() + "\n", encoding="utf-8")
    print(f"OK: wrote {out_file}")
    print(f"New/updated clips: {len(new_blocks)}")


if __name__ == "__main__":
    main()
