#!/usr/bin/env python3
"""
Build firmware/voice_fallback.h from fallback/voice_voicepackmissing.wav.

That clip ("voice pack missing") is the only one compiled into the firmware:
it is spoken at boot when the voice pack is missing or rejected. Generate the
WAV with piper/fallback_phrases.txt (see the comment there), then run this.
"""

from __future__ import annotations

import argparse
import array
import wave
from pathlib import Path

HERE = Path(__file__).resolve().parent


def main() -> None:
    ap = argparse.ArgumentParser(description="Build firmware/voice_fallback.h from the fallback clip.")
    ap.add_argument("--in", dest="in_wav", default=str(HERE / "fallback" / "voice_voicepackmissing.wav"))
    ap.add_argument("--out", default=str(HERE.parent / "voice_fallback.h"))
    ap.add_argument("--rate", type=int, default=8000, help="I2S_SAMPLE_RATE")
    args = ap.parse_args()

    with wave.open(args.in_wav, "rb") as wav_file:
        if wav_file.getnchannels() != 1 or wav_file.getsampwidth() != 2 or wav_file.getframerate() != args.rate:
            raise SystemExit(f"{args.in_wav}: expected mono PCM16 at {args.rate} Hz")
        samples = array.array("h", wav_file.readframes(wav_file.getnframes()))

    rows = [", ".join(str(s) for s in samples[i:i + 16]) for i in range(0, len(samples), 16)]
    lines = [
        "// AUTO-GENERATED by voice_assets/build_fallback_clip.py from fallback/voice_voicepackmissing.wav",
        "// \"voice pack missing\": the one clip in the firmware, for a missing or rejected voice pack.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"// Mono PCM16 at {args.rate} Hz.",
        "static const int16_t kVoicePackMissingPcm[] = {",
        *(f"  {row}," for row in rows),
        "};",
        "",
    ]
    Path(args.out).write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"OK: wrote {args.out} ({len(samples)} samples, {len(samples) * 2} B)")


if __name__ == "__main__":
    main()
