#pragma once

#include "radio_globals.h"

bool civQueryFrequency(const RadioProfile& sp, uint64_t& hzOut, uint32_t timeoutMs);
bool civSetFrequency(const RadioProfile& sp, uint64_t hz);
bool civQueryMode(const RadioProfile& sp, uint8_t& modeOut, uint32_t timeoutMs);
bool civSetMode(const RadioProfile& sp, uint8_t mode, uint8_t filter);
bool civQuerySMeterRaw(const RadioProfile& sp, int32_t& rawOut, uint32_t timeoutMs);
bool civQueryPoMeterRaw(const RadioProfile& sp, int32_t& rawOut, uint32_t timeoutMs);
bool civQuerySWRRaw(const RadioProfile& sp, int32_t& rawOut, uint32_t timeoutMs);
bool civQueryRfPowerLevel(const RadioProfile& sp, uint16_t& valueOut, uint32_t timeoutMs);
bool civSetRfPowerLevel(const RadioProfile& sp, uint16_t value);
bool civQueryNr(const RadioProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetNr(const RadioProfile& sp, bool on);
bool civQueryNrLevel(const RadioProfile& sp, uint16_t& valueOut, uint32_t timeoutMs);
bool civSetNrLevel(const RadioProfile& sp, uint16_t value);
bool civQueryNb(const RadioProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetNb(const RadioProfile& sp, bool on);
bool civQueryNbLevel(const RadioProfile& sp, uint16_t& valueOut, uint32_t timeoutMs);
bool civSetNbLevel(const RadioProfile& sp, uint16_t value);
bool civQueryNotch(const RadioProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetNotch(const RadioProfile& sp, bool on);
bool civQueryNotchWidth(const RadioProfile& sp, NotchWidth& widthOut, uint32_t timeoutMs);
bool civSetNotchWidth(const RadioProfile& sp, NotchWidth width);
bool civQueryPbtInner(const RadioProfile& sp, uint16_t& valueOut, uint32_t timeoutMs);
bool civSetPbtInner(const RadioProfile& sp, uint16_t value);
bool civQueryPbtOuter(const RadioProfile& sp, uint16_t& valueOut, uint32_t timeoutMs);
bool civSetPbtOuter(const RadioProfile& sp, uint16_t value);
bool civQueryDialLock(const RadioProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetDialLock(const RadioProfile& sp, bool on);
bool civQueryFilterShape(const RadioProfile& sp, bool& softOut, uint32_t timeoutMs);
bool civSetFilterShape(const RadioProfile& sp, bool soft);
bool civQueryFilterWidth(const RadioProfile& sp, uint8_t& rawOut, uint32_t timeoutMs);
bool civSetFilterWidth(const RadioProfile& sp, uint8_t raw);
bool civQueryMonitorEnabled(const RadioProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetMonitorEnabled(const RadioProfile& sp, bool on);
bool civQueryMonitorLevel(const RadioProfile& sp, uint16_t& valueOut, uint32_t timeoutMs);
bool civSetMonitorLevel(const RadioProfile& sp, uint16_t value);
bool civQueryTransceiveEnabled(const RadioProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetTransceiveEnabled(const RadioProfile& sp, bool on);
bool civQueryBandStackEntry(const RadioProfile& sp, uint8_t bandCode, uint8_t registerCode, BandStackEntry& entryOut, uint32_t timeoutMs);
bool civQueryTuner(const RadioProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetTuner(const RadioProfile& sp, bool on);
bool civStartTune(const RadioProfile& sp);
bool civQueryRxTxStatus(const RadioProfile& sp, bool& txOut, uint32_t timeoutMs);
bool civQueryTxFrequency(const RadioProfile& sp, uint64_t& hzOut, uint32_t timeoutMs);
bool civSelectVfoA(const RadioProfile& sp);
bool civSelectVfoB(const RadioProfile& sp);
bool civQueryVfoFrequency(const RadioProfile& sp, bool targetVfoA, uint64_t& hzOut, uint32_t timeoutMs);
bool civSetVfoFrequency(const RadioProfile& sp, bool targetVfoA, uint64_t hz);
bool civQueryVfoMode(const RadioProfile& sp, bool targetVfoA, uint8_t& modeOut, uint8_t& filterOut, uint32_t timeoutMs);
bool civSetVfoMode(const RadioProfile& sp, bool targetVfoA, uint8_t mode, uint8_t filter);
bool civQuerySplit(const RadioProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetSplit(const RadioProfile& sp, bool on);
bool civQueryRitEnabled(const RadioProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetRitEnabled(const RadioProfile& sp, bool on);
bool civQueryRitOffsetHz(const RadioProfile& sp, int32_t& hzOut, uint32_t timeoutMs);
bool civSetRitOffsetHz(const RadioProfile& sp, int32_t hz);
