#pragma once

#include "radio_globals.h"

bool civQueryFrequency(const StoredProfile& sp, uint64_t& hzOut, uint32_t timeoutMs);
bool civSetFrequency(const StoredProfile& sp, uint64_t hz);
bool civQueryMode(const StoredProfile& sp, uint8_t& modeOut, uint32_t timeoutMs);
bool civSetMode(const StoredProfile& sp, uint8_t mode, uint8_t filter);
bool civQuerySMeterRaw(const StoredProfile& sp, int32_t& rawOut, uint32_t timeoutMs);
bool civQueryPoMeterRaw(const StoredProfile& sp, int32_t& rawOut, uint32_t timeoutMs);
bool civQuerySWRRaw(const StoredProfile& sp, int32_t& rawOut, uint32_t timeoutMs);
bool civQueryNr(const StoredProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetNr(const StoredProfile& sp, bool on);
bool civQueryNrLevel(const StoredProfile& sp, uint16_t& valueOut, uint32_t timeoutMs);
bool civSetNrLevel(const StoredProfile& sp, uint16_t value);
bool civQueryNb(const StoredProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetNb(const StoredProfile& sp, bool on);
bool civQueryNbLevel(const StoredProfile& sp, uint16_t& valueOut, uint32_t timeoutMs);
bool civSetNbLevel(const StoredProfile& sp, uint16_t value);
bool civQueryNotch(const StoredProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetNotch(const StoredProfile& sp, bool on);
bool civQueryNotchWidth(const StoredProfile& sp, NotchWidth& widthOut, uint32_t timeoutMs);
bool civSetNotchWidth(const StoredProfile& sp, NotchWidth width);
bool civQueryPbtInner(const StoredProfile& sp, uint16_t& valueOut, uint32_t timeoutMs);
bool civSetPbtInner(const StoredProfile& sp, uint16_t value);
bool civQueryPbtOuter(const StoredProfile& sp, uint16_t& valueOut, uint32_t timeoutMs);
bool civSetPbtOuter(const StoredProfile& sp, uint16_t value);
bool civQueryDialLock(const StoredProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetDialLock(const StoredProfile& sp, bool on);
bool civQueryFilterShape(const StoredProfile& sp, bool& softOut, uint32_t timeoutMs);
bool civSetFilterShape(const StoredProfile& sp, bool soft);
bool civQueryFilterWidth(const StoredProfile& sp, uint8_t& rawOut, uint32_t timeoutMs);
bool civSetFilterWidth(const StoredProfile& sp, uint8_t raw);
bool civQueryMonitorEnabled(const StoredProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetMonitorEnabled(const StoredProfile& sp, bool on);
bool civQueryMonitorLevel(const StoredProfile& sp, uint16_t& valueOut, uint32_t timeoutMs);
bool civSetMonitorLevel(const StoredProfile& sp, uint16_t value);
bool civQueryTransceiveEnabled(const StoredProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetTransceiveEnabled(const StoredProfile& sp, bool on);
bool civQueryBandStackEntry(const StoredProfile& sp, uint8_t bandCode, uint8_t registerCode, BandStackEntry& entryOut, uint32_t timeoutMs);
bool civQueryTuner(const StoredProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetTuner(const StoredProfile& sp, bool on);
bool civStartTune(const StoredProfile& sp);
bool civQueryRxTxStatus(const StoredProfile& sp, bool& txOut, uint32_t timeoutMs);
bool civQueryTxFrequency(const StoredProfile& sp, uint64_t& hzOut, uint32_t timeoutMs);
bool civSelectVfoA(const StoredProfile& sp);
bool civSelectVfoB(const StoredProfile& sp);
bool civQueryVfoFrequency(const StoredProfile& sp, bool targetVfoA, uint64_t& hzOut, uint32_t timeoutMs);
bool civSetVfoFrequency(const StoredProfile& sp, bool targetVfoA, uint64_t hz);
bool civQueryVfoMode(const StoredProfile& sp, bool targetVfoA, uint8_t& modeOut, uint8_t& filterOut, uint32_t timeoutMs);
bool civSetVfoMode(const StoredProfile& sp, bool targetVfoA, uint8_t mode, uint8_t filter);
bool civQuerySplit(const StoredProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetSplit(const StoredProfile& sp, bool on);
bool civQueryRitEnabled(const StoredProfile& sp, bool& onOut, uint32_t timeoutMs);
bool civSetRitEnabled(const StoredProfile& sp, bool on);
bool civQueryRitOffsetHz(const StoredProfile& sp, int32_t& hzOut, uint32_t timeoutMs);
bool civSetRitOffsetHz(const StoredProfile& sp, int32_t hz);
