#include "ui_keypad_state.h"

uint8_t g_bank = 1;
bool g_bankSelectActive = false;
uint8_t g_bankStage = 0;
bool g_modeSetActive = false;
bool g_modeStageActive = false;
uint8_t g_modeStageMode = 0xFF;
uint8_t g_modeStageTargetVfo = 0;
char g_modeStageKey = 0;
bool g_profileSelectActive = false;
String g_profileStageDigits;
bool g_nineHoldConsumed = false;
String g_kpStagedCmd;
bool g_kpHasStagedCmd = false;
bool g_starHoldConsumed = false;
bool g_zeroHoldConsumed = false;
bool g_aHoldConsumed = false;
bool g_oneHoldConsumed = false;
bool g_twoHoldConsumed = false;
bool g_threeHoldConsumed = false;
bool g_fourHoldConsumed = false;
bool g_fiveHoldConsumed = false;
bool g_sixHoldConsumed = false;
bool g_sevenHoldConsumed = false;
bool g_eightHoldConsumed = false;
bool g_freqEntryActive = false;
String g_freqEntryDigits;
bool g_freqEntryIsMHz = false;
uint8_t g_freqEntryTargetVfo = 0;
bool g_rfPowerEntryActive = false;
String g_rfPowerEntryDigits;
Bank6EntryMode g_bank6EntryMode = BANK6_ENTRY_NONE;
String g_bank6EntryDigits;
bool g_volStageActive = false;
uint8_t g_volStageLevel = 2;
bool g_pendingClickActive = false;
uint8_t g_pendingClickBank = 0;
char g_pendingClickKey = 0;
uint32_t g_pendingClickAtMs = 0;
